language: php
php:
- 5.5
- 5.6
install: composer install
script: ./vendor/bin/phing test
after_success: ./vendor/bin/phing report-to-coveralls
notifications:
  email:
    recipients:
      - luc@2dotstwice.be
      - kristof@2dotstwice.be
      - nicoloas@2dotstwice.be
